### ISSUE TITLE
Add metube

### ISSUE THREAD

**Issue by dzahariev** [dzahariev/home-media-server-pi#33]
https://hub.docker.com/r/alexta69/metube
https://github.com/alexta69/metube

Still [no security](https://github.com/alexta69/metube/issues/217), but if implemented can be considered.

**Comment by dzahariev** [comment]
Something like this:
```
  metube:
    image: alexta69/metube:2023-02-04
    container_name: metube
    restart: always
    hostname:
      metube.${ROOT_HOST}
    volumes:
      - "${PLEX_MEDIA_DIR}/downloads:/downloads"
      - "${DATA_DIR}/metube/cookies:/cookies"
    environment:
      UID: 1000
      GID: 1000
      TZ: Europe/Sofia
      VIRTUAL_HOST: metube.${ROOT_HOST}
      LETSENCRYPT_HOST: metube.${ROOT_HOST}
      VIRTUAL_PORT: 8081
      YTDL_OPTIONS: '{"cookiefile":"/cookies/cookies.txt"}'
    depends_on:
      - acme-companion

```
